"""Add cycle_length and period_length to menstrual_cycle

Revision ID: 190cb532b8d5
Revises: 23fd3b743bd0
Create Date: 2024-06-08 15:06:26.009827

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '190cb532b8d5'
down_revision = '23fd3b743bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menstrual_cycle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cycle_length', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('period_length', sa.Integer(), nullable=False))
        batch_op.alter_column('flow_intensity',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('timestamp')
        batch_op.drop_column('fertile_window_end')
        batch_op.drop_column('notes')
        batch_op.drop_column('fertile_window_start')
        batch_op.drop_column('symptoms')
        batch_op.drop_column('ovulation_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menstrual_cycle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ovulation_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('symptoms', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('fertile_window_start', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('notes', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('fertile_window_end', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=False))
        batch_op.alter_column('flow_intensity',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('period_length')
        batch_op.drop_column('cycle_length')

    # ### end Alembic commands ###
