"""Add enhanced fields to MenstrualCycle model

Revision ID: 23fd3b743bd0
Revises: 3e0ea9773878
Create Date: 2024-06-08 12:40:14.082757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fd3b743bd0'
down_revision = '3e0ea9773878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menstrual_cycle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flow_intensity', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('symptoms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ovulation_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fertile_window_start', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fertile_window_end', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menstrual_cycle', schema=None) as batch_op:
        batch_op.drop_column('fertile_window_end')
        batch_op.drop_column('fertile_window_start')
        batch_op.drop_column('ovulation_date')
        batch_op.drop_column('symptoms')
        batch_op.drop_column('flow_intensity')

    # ### end Alembic commands ###
